/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ospp.booking.bookingfx;

/**
 *
 * @author Andreas
 */
public class BigData {
    public static String flights[][]={{"Arlanda", "ARN", "2015-06-02","13:45","Bahamas airport", "BAH", "2015-06-03","02:45"},
        {"Arlanda", "ARN", "2015-06-02","17:43","Bahamas airport", "BAH", "2015-06-03","06:43"},
        {"Arlanda", "ARN", "2015-06-02","19:45","Bahamas airport", "BAH", "2015-06-03","08:45"},
        {"Arlanda", "ARN", "2015-06-02","23:45","Bahamas airport", "BAH", "2015-06-03","12:45"}};
    public static String airports[][] = {
{"Arlanda", "ARN", "SE", "SE-ST", "001SE"},
{"Bahamas airport", "BAH", "BH", "BAHAMAS", "0049A"},
{"Total Rf Heliport","US","US-PA","Bensalem","00A"},
{"Epps Airpark","US","US-AL","Harvest","00AL"},
{"Cordes Airport","US","US-AZ","Cordes","00AZ"},
{"Cass Field","US","US-CO","Briggsdale","00CO"},
{"Ringhaver Heliport","US","US-FL","Riverview","00FD"},
{"Lt World Airport","US","US-GA","Lithonia","00GA"},
{"Kaupulehu Heliport","US","US-HI","Kailua/Kona","00HI"},
{"Bailey Generation Station Heliport","US","US-IN","Chesterton","00II"},
{"St Mary Medical Center Heliport","US","US-IN","Hobart","00IN"},
{"Hayden Farm Airport","US","US-KS","Gardner","00KS"},
{"Shell Chemical East Site Heliport","US","US-LA","Gonzales","00LA"},
{"Lejeune Airport","US","US-LA","Esterwood","00LS"},
{"Dow Chemical Heliport","US","US-MI","Ludington","00MI"},
{"Cooper Flying Service Airport","US","US-MO","Alba","00MO"},
{"Bucks Airport","US","US-NJ","Bridgeton","00N"},
{"Colgate-Piscataway Heliport","US","US-NJ","New Brunswick","00NJ"},
{"Exit 3 Airport","US","US-OH","Wauseon","00OH"},
{"Steel Systems Heliport","US","US-OR","Salem","00OR"},
{"Ferrell Field","US","US-PA","Mercer","00PN"},
{"Mc Kenzie Bridge State Airport","US","US-OR","Mc Kenzie Bridge","00S"},
{"Sw Region Faa Heliport","US","US-TX","Fort Worth","00TA"},
{"Ragsdale Road Airport","US","US-TN","Manchester","00TN"},
{"San Jacinto Methodist Hospital Heliport","US","US-TX","Baytown","00TX"},
{"Vaughan Airport","US","US-VA","Alton","00VA"},
{"Lower Granite State Airport","US","US-WA","Colfax","00W"},
{"Northern Lite Airport","US","US-WI","Waupaca","00WI"},
{"Lazy J. Aerodrome","US","US-WV","Beverly","00WV"},
{"Purkeypile Airport","US","US-AK","Purkeypile","01A"},
{"Ware Island Airport","US","US-AL","Clanton","01AL"},
{"Yat Heliport","US","US-AZ","Camp Verde","01AZ"},
{"Lugo Substation Heliport","US","US-CA","Hesperia","01CA"},
{"Los Angeles County Sheriff's Department Heliport","US","US-CA","Los Angeles","01CN"},
{"Berlin Fairgrounds Heliport","US","US-CT","Berlin","01CT"},
{"Florida Hospital-Altamonte Heliport","US","US-FL","Altamonte Springs","01FD"},
{"Medical Center Heliport","US","US-GA","Columbus","01GA"},
{"Stender Airport","US","US-IA","Maysville","01IA"},
{"Myers Field","US","US-IN","Lizton","01II"},
{"Community Hospital Heliport","US","US-IN","Anderson","01IN"},
{"Hilliard Airpark","US","US-FL","Hilliard","01J"},
{"Flying N Ranch Airport","US","US-KS","Lost Springs","01KS"},
{"Barham Airport","US","US-LA","Oak Ridge","01LA"},
{"Country Breeze Airport","US","US-LA","Slaughter","01LS"},
{"Annapolis Seaplane Base","US","US-MD","Annapolis","01MD"},
{"Flow Through Terminal Heliport","US","US-MI","Flint","01MI"},
{"Highway Patrol Troop C Headquarters Heliport","US","US-MO","Town and Country","01MO"},
{"Topsail Airpark","US","US-NC","Holly Ridge","01NC"},
{"Moore Airfield","US","US-NH","Enfield","01NH"},
{"Champion Ranch Airport","US","US-NM","Artesia","01NM"},
{"Vassar Hospital Heliport","US","US-NY","Poughkeepsie","01NY"},
{"Lawrence Airport","US","US-OK","Eakly","01OK"},
{"Pine Heliport","US","US-PA","Mars","01PA"},
{"Nort's Resort Airport","US","US-PA","Meshoppen","01PS"},
{"Thirty Thirty Matlock Office Center Heliport","US","US-TX","Arlington","01TA"},
{"Colonial Air Park","US","US-TN","Collierville","01TN"},
{"Mims Farm Ultralightport","US","US-TX","Waxahachie","01TX"},
{"La Sal Junction Airport","US","US-UT","La Sal","01UT"},
{"Willapa Harbor Heliport","US","US-WA","South Bend","01WA"},
{"Whidbey General Hospital Heliport","US","US-WA","Coupeville","01WN"},
{"Keyhole Airport","US","US-WY","Moorcroft","01WY"},
{"Meadowood Ranch Heliport","US","US-TX","Athens","01XS"},
{"Bass Field","US","US-AL","Foley","02AL"},
{"Winchester Farm Airstrip","US","US-AZ","Willcox","02AZ"},
{"Shannon Field","US","US-MS","Clarksdale","02CD"},
{"Mc Cullough Airport","US","US-CO","Monte Vista","02CO"},
{"Osborn Airfield","US","US-FL","Groveland","02FA"},
{"Doug Bolton Field","US","US-GA","Commerce","02GA"},
{"K3 Helipad Heliport","US","US-HI","Pearl Harbor","02HI"},
{"Morgan Ranch Airport","US","US-ID","Cascade","02ID"},
{"Diamond P. Field","US","US-IN","Muncie","02IN"},
{"Jmj Landing Airport","US","US-KS","St Marys","02KS"},
{"La State Police Troop G Heliport","US","US-LA","Bossier City","02LA"},
{"Cuttyhunk Heliport","US","US-MA","Gosnold","02MA"},
{"Fairplains Airpark","US","US-MI","Greenville","02MI"},
{"Troy Airpark","US","US-MO","Troy","02MO"},
{"Barrett Field","US","US-MT","Cascade","02MT"},
{"Race City Heliport","US","US-NC","Landis","02NC"},
{"Iroquois Landing Seaplane Base","US","US-NH","Dummer","02NH"},
{"Paiute Meadows Airport","US","US-NV","Winnemucca","02NV"},
{"Zimmerman Airport","US","US-OH","Fremont","02OH"},
{"Canon Heliport","US","US-OK","Oklahoma City","02OK"},
{"Stottle Memorial Heliport","US","US-PA","Honey Grove","02P"},
{"Peco Berwyn Heliport","US","US-PA","Berwyn","02PN"},
{"Hughes Ultralightport","US","US-PA","Tioga","02PS"},
{"Wise River Airport","US","US-MT","Wise River","02T"},
{"Baylor Medical Center Heliport","US","US-TX","Waxahachie","02TE"},
{"Fwomc Heliport","US","US-TX","Fort Worth","02TS"},
{"Lucin Airport","US","US-UT","Lucin","02UT"},
{"Northstar Aviation Heliport","US","US-VA","Bristol","02VG"},
{"Beer Airport","US","US-WI","Hudson","02WI"},
{"Seidel Ranch Airport","US","US-TX","Elroy","02XS"},
{"Jackson County Hospital Heliport","US","US-AL","Scottsboro","03AL"},
{"Thompson International Aviation Airport","US","US-AZ","Hereford","03AZ"},
{"Kugel-Strong Airport","US","US-CO","Platteville","03CO"},
{"Tharpe Airport","US","US-FL","Bonifay","03FD"},
{"Clarks Dream Strip","US","US-OH","Circleville","03I"},
{"Flying Y Ranch Airport","US","US-ID","Council","03ID"},
{"Wix Airport","US","US-IL","Monee","03IL"},
{"St Anthony's Hospital Heliport","US","US-IL","Alton","03IS"},
{"Flying H Farms Airport","US","US-KY","Henderson","03KY"},
{"Fmc Nr 1 Heliport","US","US-LA","Winnsboro","03LS"},
{"Hadley Airport","US","US-MA","Hadley","03MA"},
{"Maple Ridge Airport","US","US-ME","Harrison","03ME"},
{"Nauerth Land Ranch Airport","US","US-MN","Lakefield","03MN"},
{"Vicksburg Medical Center Heliport","US","US-MS","Vicksburg","03MS"},
{"Mc Donnell Airport","US","US-MO","Archie","03MU"},
{"Pilots Ridge Airport","US","US-NC","Carolina Beach","03NC"},
{"Hyde Ranch Airport","US","US-NE","Comstock","03NE"},
{"At&T Heliport","US","US-NJ","Berkely Heights","03NJ"},
{"Talmage Field","US","US-NY","Riverhead","03NY"},
{"Marymount Hospital Heliport","US","US-OH","Garfield Heights","03OI"},
{"Powwatka Ridge Airport","US","US-OR","Troy","03OR"},
{"M.P. Metals Heliport","US","US-PA","Berwick","03PN"},
{"Sandy River Airport","US","US-OR","Sandy","03S"},
{"Gay Hill Farm Airport","US","US-TX","Gay Hill","03TA"},
{"Eagles Landing Heliport","US","US-TN","Sevierville","03TN"},
{"M D K Field","US","US-TX","Pearland","03TX"},
{"Whipoorwill Springs Airport","US","US-VA","Nokesville","03VA"},
{"Zink Airport","US","US-WI","Berlin","03WI"},
{"Creekside Airport","US","US-TX","Mertzon","03XS"},
{"Saline Memorial Hospital Heliport","US","US-AR","Benton","04AR"},
{"Gray Butte Field","US","US-CA","Palmdale","04CA"},
{"Shingle Mill Heliport","US","US-CT","Harwinton","04CT"},
{"Richards Field","US","US-FL","Homestead","04FA"},
{"Columbus Southwest Airport","US","US-OH","Columbus","04I"},
{"Lanham Field","US","US-ID","Emmett","04ID"},
{"Schertz Aerial Service - Hudson Airport","US","US-IL","Hudson","04IL"},
{"Van Gorder Airport","US","US-IL","Mansfield","04IS"},
{"Natchez Trace Farm Airport","US","US-KY","Hiseville","04KY"},
{"Brunner Airport","US","US-IL","West Dundee","04LL"},
{"Goddard Field (Airport)","US","US-MA","Haverhill","04MA"},
{"Beech Hill Airport","US","US-ME","Mercer","04ME"},
{"Helblad Airport","US","US-MN","Kelliher","04MN"},
{"Nick's Flying Service Inc Airport","US","US-MS","Rolling Fork","04MS"},
{"Western Wake Medical Center Heliport","US","US-NC","Cary","04NC"},
{"Emmanuel Airport","US","US-NJ","Elmer","04NJ"},
{"Klaverack Airport","US","US-NY","Hudson","04NY"},
{"Bossow Airport","US","US-OH","Garrettsville","04OH"},
{"Collins Landing Strip","US","US-OR","Mitchell","04OR"},
{"Strawbridge & Clothier Exton Heliport","US","US-PA","Exton","04PN"},
{"Capitol National Bank Building Heliport","US","US-TX","Austin","04TA"},
{"Hensley Airpark","US","US-TN","Chuckey","04TN"},
{"Pocock Airport","US","US-TX","China Spring","04TX"},
{"Saguache Municipal Airport","US","US-CO","Saguache","04V"},
{"Manquin Flight Park Ultralightport","US","US-VA","Manquin","04VG"},
{"Field of Dreams Airport","US","US-MN","Hinckley","04W"},
{"Dutch Gap Airstrip","US","US-WI","Bristol","04WI"},
{"West Virginia Univ. Hosp. Inc. Gnd. Pad #2 Heliport","US","US-WV","Morgantown","04WV"},
{"Wasilla Creek Airpark","US","US-AK","Palmer","05AK"},
{"Ozark Skies Airpark","US","US-AR","Kingston","05AR"},
{"Van Buren Seaplane Base","US","US-ME","Van Buren","05B"},
{"Pope Valley Airport","US","US-CA","Pope Valley","05CL"},
{"O And G Heliport","US","US-CT","Torrington","05CT"},
{"Aventura Heliport","US","US-FL","North Miami Beach","05FD"},
{"Raju Airport","US","US-GA","Richland","05GA"},
{"Running Creek Ranch Airport","US","US-ID","Grangeville","05ID"},
{"Classic Landings Airport","US","US-IL","Bonfield","05IL"},
{"Hardy Airport","US","US-IL","Mount Auburn","05IS"},
{"Cartersville Airport","US","US-KY","Berea","05KY"},
{"Midwest Heliport","US","US-IL","Willowbrook","05LL"},
{"Pauls Valley General Hospital Heliport","US","US-OK","Pauls Valley","05M"},
{"Breezecroft Airport","US","US-MD","Chestertown","05MD"},
{"Portageville Community Heliport","US","US-MO","Portageville","05MO"},
{"Brunswick Community Hospital Heliport","US","US-NC","Supply","05NC"},
{"Stumpfield Heliport","US","US-NH","Kensington","05NH"},
{"Oswego County At Pulaski Heliport","US","US-NY","Pulaski","05NY"},
{"Hawk Haven Airport","US","US-OK","Crescent","05OK"},
{"Philadelphia Market Street Heliport","US","US-PA","Philadelphia","05PA"},
{"Mills Brothers Airport","US","US-PA","Burnt Cabins","05PS"},
{"Brandes Air Field","US","US-TX","Sealy","05TA"},
{"Thurmond Glenn Field","US","US-TN","Covington","05TN"},
{"Circle 'A' Ranch Airport","US","US-TX","Blum","05TX"},
{"Blanca Airport","US","US-CO","Blanca","05V"},
{"Port of Highgate Springs Heliport","US","US-VT","Highgate Springs","05VT"},
{"Ames Private Airport","US","US-WI","Darien","05WI"},
{"Johnson Memorial Airport","US","US-AR","Wilmot","05XS"},
{"June Lake Airpark","US","US-AK","Wasilla","06AK"},
{"Bondair Airport","US","US-AR","Higden","06AR"},
{"Lucky Landing Marina and Seaplane Base","US","US-ME","Bangor","06B"},
{"Abc7-Tv Heliport","US","US-CA","Glendale","06CL"},
{"William P Gwinn Airport","US","US-FL","Jupiter","06FA"},
{"Morton Plant Hospital Heliport","US","US-FL","Clearwater","06FL"},
{"Patoka Reservoir Landing Area Seaplane Base","US","US-IN","French Lick","06I"},
{"Larkin Airport","US","US-ID","Kuna","06ID"},
{"Ellis Fly-In Airport","US","US-IN","Blackhawk","06IN"},
{"Riverside Hospital Airlift Heliport","US","US-KS","Wichita","06KS"},
{"Panther Helicopters Inc Heliport","US","US-LA","Belle Chasse","06LA"},
{"Tembec Heliport","US","US-LA","St Francisville","06LS"},
{"Bayview Heliport","US","US-MD","Baltimore","06MD"},
{"Pike Field Airport","US","US-MN","Virginia","06MN"},
{"Torgerson Airport","US","US-MT","Ethridge","06MT"},
{"Tailwinds Airport","US","US-NC","St. Pauls","06NC"},
{"St Marys Hospital Heliport","US","US-NE","Nebraska City","06NE"},
{"Chemical Bank - New Jersey Na Heliport","US","US-NJ","Moorestown","06NJ"},
{"Saint Elizabeth Medical Center Heliport","US","US-OH","Youngstown","06O1"},
{"Green Acres Airport","US","US-OH","New Lebanon","06OI"},
{"Hayden Mountain Airport","US","US-OR","Forest Grove","06OR"},
{"Schiavoni Heliport","US","US-PA","Harrisburg","06PN"},
{"Grawunder Field","US","US-TX","Bellville","06R"},
{"Glaser Field","US","US-TX","Buckholts","06TA"},
{"Hunter STOLport","US","US-TN","Columbia","06TN"},
{"Diamond N Ranch Airport","US","US-TX","Hockley","06TX"},
{"N A Degerstrom Yard Heliport","US","US-WA","Spokane","06WA"},
{"Western Airpark","US","US-WA","Yelm","06WN"},
{"Herman Municipal Airport","US","US-MN","Herman","06Y"},
{"Morrilton Airport","US","US-AR","Morrilton","07AR"},
{"Blue Hill Airport","US","US-ME","Blue Hill","07B"},
{"Richvale Airport","US","US-CA","Richvale","07CL"},
{"Tnt Heliport","US","US-CT","Salem","07CT"},
{"Ocean Reef Club Airport","US","US-FL","Key Largo","07FA"},
{"Southwest Florida Regional Medical Center Heliport","US","US-FL","Fort Myers","07FL"},
{"Lake Monroe Seaplane Base","US","US-IN","Bloomington","07I"},
{"St Vincent Jennings Hospital Heliport","US","US-IN","North Vernon","07II"},
{"Central City Municipal - Larry Reineke Field","US","US-NE","Central City","07K"},
{"Blue Lick Airport","US","US-KY","Louisville","07KY"},
{"LA State Police Troop F Heliport","US","US-LA","Monroe","07LS"},
{"Baugher's Orchard Airport","US","US-MD","Westminster","07MD"},
{"Scott Airstrip","US","US-MI","Lake","07MI"},
{"Lake Sexton Airport","US","US-MO","Warrensburg","07MO"},
{"Bermudian Valley Airpark","US","US-PA","Kralltown","07N"},
{"Diving Rock Seaplane Base","US","US-NH","Washington","07NH"},
{"Mmc Heliport","US","US-NY","Monticello","07NY"},
{"Pleasant Valley Airport","US","US-OK","Snyder","07OK"},
{"Folmar Airport","US","US-PA","Grassflat","07PN"},
{"Salaika Aviation Airport","US","US-TX","Danbury","07TA"},
{"Corntassel Airport","US","US-TN","Vonore","07TN"},
{"Pecks Heliport","US","US-TX","Princeton","07TX"},
{"Alpha Hotel Airport","US","US-VA","Clover","07VA"},
{"Deaconess Medical Center Heliport","US","US-WA","Spokane","07WA"},
{"Allen Ponderosa Heliport","US","US-TX","Crowley","07XS"},
{"Fisher Airport","US","US-AK","Big Lake","08AK"},
{"Mesa Police Heliport","US","US-AZ","Mesa","08AZ"},
{"Pg & E Co. Placerville Svc Center Heliport","US","US-CA","Diamond Springs","08CA"},
{"Tulare Motor Sports #1 Heliport","US","US-CA","Tulare","08CN"},
{"Seavair's Landing Seaplane Base","US","US-CT","Winsted","08CT"},
{"Duda Airstrip","US","US-FL","La Belle","08FA"},
{"J. H. Hendrie Farms Airport","US","US-FL","Lake Placid","08FL"},
{"Sapelo Island Airport","US","US-GA","Darien","08GA"},
{"Lagrange Hospital Heliport","US","US-IN","Lagrange","08II"},
{"Winona Lake Seaplane Base","US","US-IN","Winona Lake","08IN"},
{"Alderson Airport","US","US-KS","Bennington","08KS"},
{"Air Oil Inc Nr 2 Heliport","US","US-LA","Harahan","08LA"},
{"Aeleron Airport","US","US-LA","Grand Coteau","08LS"},
{"St Joseph Hospital Heliport","US","US-MD","Towson","08MD"},
{"Sparrow Hospital Heliport","US","US-MI","Lansing","08MI"},
{"Twin Oaks Airport","US","US-MO","Jasper","08MO"},
{"Clark Airport","US","US-MT","Grassrange","08MT"},
{"Whiteheart Farm Airport","US","US-NC","Lewisville","08NC"},
{"Laurel Municipal Airport","US","US-NE","Laurel","08NE"},
{"St Barnabas Medical Center Heliport","US","US-NJ","Livingston","08NJ"},
{"Kenley Airport","US","US-OH","Hartford","08OH"},
{"Saxon Sycan Airport","US","US-OR","Silver Lake","08OR"},
{"Thomson Heliport","US","US-PA","Lancaster","08PN"},
{"Rancho Del Lago Heliport","US","US-TX","Fischer","08TA"},
{"Puesta Del Sol Airport","US","US-TX","La Gloria","08TS"},
{"Stevens-Crosby Airport","US","US-NV","North Fork","08U"},
{"Manchester Laboratory Heliport","US","US-WA","Manchester","08WA"},
{"Peterson Airport","US","US-TX","Old Ocean","08XS"},
{"Magnolia Hospital Heliport","US","US-AR","Magnolia","09AR"},
{"Mee Memorial Hospital Heliport","US","US-CA","King City","09CA"},
{"Tulare Motor Sports #2 Heliport","US","US-CA","Tulare","09CN"},
{"Placid Lakes Airport","US","US-FL","Lake Placid","09FA"},
{"Sunnybreeze Airport","US","US-FL","Arcadia","09FL"},
{"International Falls Seaplane Base","US","US-MN","International Falls","09I"},
{"Taylor Ranch Landing Area Airport","US","US-ID","Moscow","09ID"},
{"Silver Cross Hospital Heliport","US","US-IL","Joliet","09IL"},
{"Swedish American Heliport","US","US-IL","Rockford","09IS"},
{"Baptist Hospital East Heliport","US","US-KY","Louisville","09KY"},
{"Pine Hill Airport","US","US-IL","Capron","09LL"},
{"Kallander Field","US","US-MA","Southborough","09MA"},
{"Michigan National Guard Headquarters Heliport","US","US-MI","Lansing","09MI"},
{"Hogue Farm Airport","US","US-MO","Willard","09MO"},
{"William Irving Lewis Airport","US","US-NC","Broadway","09NC"},
{"Stonebridge Farm Helistop","US","US-NJ","Somerville","09NJ"},
{"Ragtime Aerodrome","US","US-OK","Collinsville","09OK"},
{"Eagle Field","US","US-PA","Port Matilda","09PA"},
{"Sullivan Lake State Airport","US","US-WA","Metaline Falls","09S"},
{"Running M Ranch Airport","US","US-TX","Glen Rose","09TE"},
{"Pitcock Rosillos Mountain Ranch Airport","US","US-TX","Marathon","09TS"},
{"Alum Ridge STOLport","US","US-VA","Floyd","09VA"},
{"South Capitol Street Heliport","US","US-DC","Washington","09W"},
{"Parkway Farm Strip","US","US-WI","Holmen","09WI"},
{"Wipline Seaplane Base","US","US-MN","Inver Grove Hgts","09Y"},
{"Scotts Airport","US","US-AK","North Pole","0AK0"},
{"Yentna Bend Strip","US","US-AK","Willow","0AK2"},
{"Young Creek Airport","US","US-AK","May Creek","0AK5"},
{"Bradley Lake Hydroelectri Project Airstrip","US","US-AK","Homer","0AK7"},
{"Falcon Lake Strip","US","US-AK","Point Mackenzie","0AK9"},
{"Resort Airport","US","US-AL","Foley","0AL1"},
{"Hospital Pad Heliport","US","US-AL","Evergreen","0AL3"},
{"Flomaton Airport","US","US-AL","Flomaton","0AL5"},
{"Gadsden Regl Medical Center Heliport","US","US-AL","Gadsden","0AL7"},
{"Wilson Creek Airport","US","US-AL","Florence","0AL9"},
{"Hooterville South Airport","US","US-AR","Centerville","0AR1"},
{"Taylor's Air Strip","US","US-AR","Deer","0AR3"},
{"Rgnl Medical Center Heliport","US","US-AR","Jonesboro","0AR5"},
{"Yancopin Airport","US","US-AR","Watson","0AR7"},
{"Eureka Springs Hospital Heliport","US","US-AR","Eureka Springs","0AR9"},
{"Taylor Field","US","US-AZ","Marana","0AZ1"},
{"Flying Bucket Ranch Airport","US","US-AZ","Mobile","0AZ4"},
{"St Joseph's Hospital Heliport","US","US-AZ","Phoenix","0AZ6"},
{"Brewer Airport","US","US-ME","Brewer","0B2"},
{"Triple R Airport","US","US-MO","Dearborn","0C1"},
{"Canadian Lakes Airport","US","US-MI","Mecosta","0C5"},
{"Cushing Field Ltd Airport","US","US-IL","Newark","0C8"},
{"Drew Medical Center Heliport","US","US-CA","Los Angeles","0CA0"},
{"Va Greater Los Angeles Health Care Center Heliport","US","US-CA","West Los Angeles","0CA2"},
{"Shepherd Ranch Airport","US","US-CA","Santa Ynez","0CA4"},
{"Emory Ranch Airport","US","US-CA","Ocotillo","0CA6"},
{"Ward Ranch Airport","US","US-CA","Aguanga","0CA8"},
{"Delta County Memorial Hospital Heliport","US","US-CO","Delta","0CD0"},
{"Foxx Valley Airport","US","US-CO","Yoder","0CD2"},
{"Kauffman Heliport","US","US-CO","Denver","0CD4"},
{"Exempla Good Samaritan Heliport","US","US-CO","Lafayette","0CD6"},
{"Prowers Medical Center Heliport","US","US-CO","Lamar","0CD8"},
{"Yosemite Hidden Lake Ranch Airport","US","US-CA","Raymond","0CL0"},
{"Parking Lot Heliport","US","US-CA","Chula Vista","0CL2"},
{"Glen Fed Heliport","US","US-CA","Glendale","0CL4"},
{"Bohunk's Airpark","US","US-CA","Lancaster","0CL6"},
{"Tera Ultralightport","US","US-CA","Ridgecrest","0CL8"},
{"Longmont United Hospital Heliport","US","US-CO","Longmont","0CO0"},
{"Buckhorn Ranch Airport","US","US-CO","Crested Butte","CSE"},
{"Sally Wofford Airport","US","US-AR","Weiner","8M2"},
{"Tradewater Airport","US","US-KY","Dawson Springs","8M7"},
{"Rite Aid Distribution Center Heliport","US","US-MD","Aberdeen","8MD1"},
{"Sinai Ii Heliport","US","US-MD","Baltimore","8MD3"},
{"Harrison Farm Airport","US","US-MD","Libertytown","8MD5"},
{"Deerfield Airport","US","US-MD","Leonardtown","8MD7"},
{"B & G Heliport","US","US-MI","Grand Rapids","8MI1"},
{"Mattawan Airpark","US","US-MI","Mattawan","8MI3"},
{"Consumers Power Company Heliport","US","US-MI","South Haven","8MI5"},
{"Bass Lake Airport","US","US-MI","Steuben","8MI7"},
{"Winters Field","US","US-MI","Chelsea","8MI9"},
{"Stewart Farms Airport","US","US-MN","Cannon Falls","8MN1"},
{"Sethney Personal STOLport","US","US-MN","Deerwood","8MN4"},
{"St Elizabeth Hospital Heliport","US","US-MN","Wabasha","8MN7"},
{"Mavencamp Airport","US","US-MN","Maple Lake","8MN9"},
{"Liberty Hospital Heliport","US","US-MO","Liberty","8MO2"},
{"Joan Lake Airport","US","US-MO","Richwoods","8MO4"},
{"Pike County Memorial Hospital Heliport","US","US-MO","Louisiana","8MO6"},
{"Frazier Airport","US","US-MO","Monett","8MO8"},
{"Rockingham County Heliport","US","US-NC","Eden","8N0"},
{"Flying Dollar Airport","US","US-PA","Canadensis","8N4"},
{"Tappen Airstrip","US","US-ND","Tappen","8NA0"},
{"Liechty Farm Airport","US","US-ND","Montpelier","8NA5"},
{"Hashbarger Farm Airstrip","US","US-ND","Hope","8NA9"},
{"Dean Wings Past Airport","US","US-NC","Cameron","8NC1"},
{"Winding Creek Airport","US","US-NC","Sneads Ferry","8NC3"},
{"Adams Airport","US","US-NC","Rowland","8NC5"},
{"Parker Field","US","US-NC","Maysville","8NC7"},
{"W.N.C. Air Museum Airport","US","US-NC","Hendersonville","8NC9"},
{"Heyde Airport","US","US-ND","Manvel","8ND4"},
{"J Vining Airport","US","US-ND","Chaffee","8ND6"},
{"Smith Field","US","US-NE","Champion","8NE3"},
{"X1 Ranch Airport","US","US-NE","Ericson","8NE5"},
{"Smith Airport","US","US-NE","Franklin","8NE7"},
{"Winchelsea Airport","US","US-NJ","Port Republic","8NJ0"},
{"Carnegie Center Heliport","US","US-NJ","Princeton","8NJ2"},
{"South Jersey Hospital System Heliport","US","US-NJ","Bridgeton","8NJ4"},
{"Lamington House Heliport","US","US-NJ","Bedminster","8NJ6"},
{"Kraemer Heliport","US","US-NJ","Richwood","8NJ8"},
{"Marine Helicopter Squadron 361 Heliport","US","US-NY","Jamesport","8NK2"},
{"Bethany Airpark","US","US-NY","Bethany Center","8NK4"},
{"Suntime Airport","US","US-NY","West Burlington","8NK6"},
{"James Carl Memorial Heliport","US","US-NY","Roscoe","8NY1"},
{"North Fork Airport","US","US-NY","Afton","8NY3"},
{"Sha-Wan-Ga Valley Airport","US","US-NY","Bloomingburg","8NY7"},
{"The Jewish Hospital Heliport","US","US-OH","Cincinnati","8OA3"},
{"Warner Airstrip","US","US-OH","Vickery","8OA6"},
{"Margos Sky Ranch Airport","US","US-OH","Seville","8OA9"},
{"Dunlap Memorial Hospital Heliport","US","US-OH","Orrville","8OH1"},
{"J and B Sky Ranch Airport","US","US-OH","Coitsville","8OH3"},
{"Urban Airport","US","US-OH","Cortland","8OH5"},
{"Morris Field","US","US-OH","East Palestine","8OH7"},
{"University Hospital/Sicu Heliport","US","US-OH","Cincinnati","8OH9"},
{"Allen Airport","US","US-OH","Cortland","8OI3"},
{"Clum Airport","US","US-OH","Thornville","8OI5"},
{"Meridia Huron Hospital Heliport","US","US-OH","East Cleveland","8OI8"},
{"Lamle Airport","US","US-OK","Okeene","8OK0"},
{"Baker Airstrip","US","US-OK","El Reno","8OK2"},
{"Brandley Airport","US","US-OK","El Reno","8OK4"},
{"Barry Dotson Ranch Airport","US","US-OK","Marble City","8OK6"},
{"Baptist Regional Health Center Heliport","US","US-OK","Miami","8OK8"},
{"Petes Airpark","US","US-OK","Wetumka","8OL1"},
{"Lebanon Hospital Heliport","US","US-OR","Lebanon","8OR1"},
{"Riverview Ranch Airport","US","US-OR","Days Creek","8OR3"},
{"Pilot Butte Airport","US","US-OR","Bend","8OR5"},
{"Gates Airport","US","US-OR","Corvallis","8OR7"},
{"Samaritan Pacific Communities Hospital Heliport","US","US-OR","Newport","8OR9"},
{"Dee Jay Airport","US","US-PA","Ono","8PA1"},
{"Deer Meadows Airstrip","US","US-PA","Weatherly","8PA3"},
{"Echo 8 Communications Facility Heliport","US","US-PA","Kittanning","8PA5"},
{"Sunny Rest Airport","US","US-PA","Palmerton","8PA8"},
{"Lost Acres Airport","US","US-PA","Chambersburg","8PN0"},
{"Mc Cauley'S Airport","US","US-PA","Venus","8PN3"},
{"Helfrick Heliport","US","US-PA","Elysburg","8PN5"},
{"Cameron County Junior/Senior High School Heliport","US","US-PA","Emporium","8PN7"},
{"Marsh Creek Airport","US","US-PA","Gettysburg","8PN9"},
{"Bethlehem Steel Plant Heliport","US","US-PA","Bethlehem","8PS1"},
{"Empire Heliport","US","US-PA","Taylor","8PS3"},
{"Community Medical Center Heliport","US","US-PA","Scranton","8PS7"},
{"Travis Air Force Base Aero Club","US","US-CA","Fairfield","8Q0"},
{"Santiam Junction State Airport","US","US-OR","Santiam Junction","8S3"},
{"John B Connally Ranch Airport","US","US-TX","Floresville","8TA0"},
{"Department of Public Safety Heliport","US","US-TX","Sherman","8TA2"},
{"Laseair Airport","US","US-TX","Texas City","8TA4"},
{"Hyco Heliport Nr 3 Heliport","US","US-TX","Beaumont","8TA6"},
{"Bufords Field","US","US-TX","Huntington","8TA8"},
{"Hamilton (Chedoke-McMaster Hospital) Heliport","CA","CA-ON","Hamilton","CPJ3"},
{"Stirling Airport","CA","CA-ON","Stirling","CPJ5"},
{"Manitowaning Seaplane Base","CA","CA-ON","","CPJ9"},
{"Hamilton (General Hospital) Heliport","CA","CA-ON","Hamilton","CPK3"},
{"Ottawa (Children's Hospital) Heliport","CA","CA-ON","Ottawa","CPK7"},
{"Arthur (Peskett Field)","CA","CA-ON","",""},
{"Kars / Rideau Valley Air Park","CA","CA-ON","Kars","CPL3"},
{"Thessalon Municipal Airport","CA","CA-ON","Thessalon","CPL5"},
{"Bowmanville (Memorial Hospital) Heliport","CA","CA-ON","Bowmanville","CPL7"},
{"Brampton (National P) Heliport","CA","CA-ON","Brampton","CPM2"},
{"Volk Airport","CA","CA-ON","Tottenham","CPM5"},
{"Moose Factory Heliport","CA","CA-ON","Moose Factory","CPN3"},
{"Listowel Airport","CA","CA-ON","Listowel","CPN5"},
{"Carleton Place (District Memorial Hospital) Heliport","CA","CA-ON","Carleton Place","CPN7"},
{"Port Perry / Hoskin","CA","CA-ON","",""},
{"Ottawa (Civic Hospital) Heliport","CA","CA-ON","Ottawa","CPP7"},
{"Lefroy Airport","CA","CA-ON","Lefroy","CPQ4"},
{"Skeleton Lake Seaplane Base","CA","CA-ON","","CPQ7"},
{"Palmerston Airport","CA","CA-ON","Palmerston","CPR3"},
{"Woodstock Airport","CA","CA-ON","Woodstock","CPR5"},
{"Pincher Creek (Hospital) Heliport","CA","CA-AB","Pincher Creek","CPR8"},
{"Parry Sound Harbour Seaplane Base","CA","CA-ON","","CPS1"},
{"Lucan Airport","CA","CA-ON","Lucan","CPS4"},
{"Cornwall (Community Hospital McConnell Site) Heliport","CA","CA-ON","Cornwall","CPS6"},
{"Parry Sound/Huron Island Seaplane Base","CA","CA-ON","","CPS8"},
{"Killarney Airport","CA","CA-ON","Killarney","CPT2"},
{"Barrie/Little Lake Seaplane Base","CA","CA-ON","","CPT5"},
{"Mattawa Seaplane Base","CA","CA-ON","","CPT7"},
{"Kincardine (South Bruce Grey Health Centre Hospital) Heliport","CA","CA-ON","Kincardine","CPU2"},
{"London (Victoria Hospital) Heliport","CA","CA-ON","London","CPW2"},
{"Timmins/Porcupine Lake Seaplane Base","CA","CA-ON","","CPW5"},
{"Powell River (Hospital) Heliport","CA","CA-BC","Powell River","CPW8"},
{"Marathon (Wilson Memorial Hospital) Heliport","CA","CA-ON","Marathon","CPX2"},
{"Port Colborne (General Hospital) Heliport","CA","CA-ON","Port Colborne","CPX5"},
{"Sault Ste. Marie Seaplane Base","CA","CA-ON","","CPX8"},
{"Beardmore (Health Centre) Heliport","CA","CA-ON","Beardmore","CPY3"},
{"Wilson's Heliport","CA","CA-ON","Toronto","CPY5"},
{"Port Carling/Butterfly Lake Seaplane Base","CA","CA-ON","","CPY8"},
{"Alliston (Stevenson Memorial Hospital) Heliport","CA","CA-ON","Alliston","CPZ2"},
{"Montreal / Point Zero","CA","CA-QC","","PZ6"},
{"Toronto/City Centre Seaplane Base","CA","CA-ON","","CPZ9"},
{"Rivière Bonnard Airport","CA","CA-QC","Rivière Bonnard","CRB4"},
{"Cardinal Aviation Seaplane Base","CA","CA-QC","Rivière Blanche","CRB7"},
{"Red Deer Regional Hospital Centre Heliport","CA","CA-AB","Red Deer","CRD3"},
{"Red Deer / Truant Airfield","CA","CA-AB","",""},
{"Curries (Rand Private Airfield)","CA","CA-ON","","CRE3"},
{"Edmonton / Villeneuve (Rose Field)","CA","CA-AB","Villeneuve","CRF3"},
{"Coronation (Health Centre) Heliport","CA","CA-AB","Coronation","CRH2"},
{"Stoney Point (Trepanier)","CA","CA-ON","",""},
{"Red Lake (Margaret Cochenour Memorial Hospital) Heliport","CA","CA-ON","Red Lake","CRL3"},
{"Reindeer Lake / Lindbergh Lodge Airstrip","CA","CA-SK","",""},
{"Stoney Point (Le Cunff) Airport","CA","CA-ON","Stoney Point","CRML"},
{"Parry Sound Medical Heliport","CA","CA-ON","Parry Sound","CRS2"},
{"Matoush Airport","CA","CA-QC","",""},
{"Barrie (Royal Victoria Hospital) Heliport","CA","CA-ON","Barrie","CRV2"},
{"Redwater (Heliworks)","CA","CA-AB","","CRW2"},
{"Lac Agile (Mascouche) Airport","CA","CA-QC","Lac Agile","CSA2"},
{"Boisvert & Fils Seaplane Base","CA","CA-QC","Montréal","CSA4"},
{"Lac-Des-Îles Seaplane Base","CA","CA-QC","","CSA9"},
{"St-Mathieu-De-Beloeil Airport","CA","CA-QC","St-Mathieu-De-Beloeil","CSB3"},
{"Shediac Bridge Airport","CA","CA-NB","Shediac Bridge","CSB5"},
{"Parc De La Vérendrye (Le Domaine) Seaplane Base","CA","CA-QC","","CSB9"},
{"Lac Etchemin Airport","CA","CA-QC","Lac Etchemin","CSC5"},
{"Sudbury / Coniston Airport","CA","CA-ON","Sudbury","CSC9"},
{"Valleyfield Airport","CA","CA-QC","Valleyfield","CSD3"},
{"Fermont Heliport","CA","CA-QC","Fermont","CSD5"},
{"Parc Gatineau Seaplane Base","CA","CA-QC","La Peche","CSD9"},
{"Lourdes-De-Joliette Airport","CA","CA-QC","Lourdes-De-Joliette","CSE3"},
{"Montmagny Airport","CA","CA-QC","Montmagny","CSE5"},
{"Delta (SEI) Heliport","CA","CA-BC","Vancouver","CSE7"},
{"Parent Seaplane Base","CA","CA-QC","","CSE9"},
{"Ste-Marguerite Heliport","CA","CA-QC","Ste-Marguerite","CSF6"},
{"Lac Kaiagamac Seaplane Base","CA","CA-QC","","CSF8"},
{"Joliette Airport","CA","CA-QC","Joliette","CSG3"},
{"Edmonton / Kelsonae Heliport","CA","CA-AB","","CSG6"},
{"Témiscaming/Lac Kipawa Seaplane Base","CA","CA-QC","","CSG8"},
{"Lebel-sur-Quevillon Airport","CA","CA-QC","Lebel-sur-Quévillon","CSH4"},
{"Montreal / Les Cèdres Heliport","CA","CA-QC","Montréal","CSH6"},
{"Montréal East (Aim) Heliport","CA","CA-QC","Montréal","CSH9"},
{"Louiseville Airport","CA","CA-QC","Louiseville","CSJ4"},
{"Montreal / Mascouche Airport","CA","CA-QC","Montréal","CSK3"},
{"Paquet Airport","CA","CA-QC","St-Raymond","CSK5"},
{"King George Airpark","CA","CA-BC","Surrey","CSK8"},
{"O'Sullivan Army Heliport","US","US-CA","Camp San Luis Obispo","CSL"},
{"Lac a la Tortue Airport","CA","CA-QC","Lac-à-la-Tortue","CSL3"},
{"Slave Lake / Slave Lake Helicopters","CA","CA-BC","",""},
{"Sudbury / Laurentian (Hospital)","CA","CA-ON","",""},
{"Thetford Mines Airport","CA","CA-QC","Thetford Mines","CSM3"},
{"St-Michel-Des-Saints Airport","CA","CA-QC","St-Michel-Des-Saints","CSM5"},
{"Abbotsford (Sumas Mountain)","CA","CA-BC","",""},
{"Montreal / Kruger Heliport","CA","CA-QC","Montréal","CSN2"},
{"Stanhope Airport","CA","CA-QC","Stanhope","CSN5"},
{"Farnham Airport","CA","CA-QC","Farnham","CSN7"},
{"Baie-Comeau / Héli-Manicouagan Heliport","CA","CA-QC","Baie-Comeau","CSN9"},
{"Stony Plain (Westview Health Centre) Heliport","CA","CA-AB","Stony Plain","CSP2"},
{"St-Mathias Airport","CA","CA-QC","St-Mathias","CSP5"},
{"Lac Sept-Îles Seaplane Base","CA","CA-QC","","CSP8"},
{"Shuswap (Skwlax Field) Airport","CA","CA-BC","",""},
{"Campbell Airstrip","US","US-AK","Anchorage","CSR"},
{"Rimouski (Hydro-Québec) Heliport","CA","CA-QC","Rimouski","CSR4"},
{"Sonora Resort Heliport","CA","CA-BC","Sonora Resort","CSR6"},
{"Rivière-du-Loup Heliport","CA","CA-QC","Rivière-du-Loup","CSS2"},
{"St-Dominique Airport","CA","CA-QC","St-Dominique","CSS4"},
{"Montreal / Marina Venise","CA","CA-QC","","ST2"},
{"Sorel-Tracy/Air Nature Inc. (Heli)","CA","CA-QC","",""},
{"Clova/Lac Duchamp Seaplane Base","CA","CA-QC","","CST6"},
{"Vinaròs Airfield","ES","ES-CS","Vinaròs",""},
{"Banco de España Helipad","ES","ES-M","Madrid",""},
{"Salamanca Fire Station Helipad","ES","ES-SA","Salamanca",""},
{"Torremocha de Jiloca Airport","ES","ES-TE","Torremocha de Jiloca",""},
{"Villoldo Airport","ES","ES-P","Villoldo",""},
{"Chaira Airport","ES","ES-OR","Baños de Molgas",""},
{"Godos Airport","ES","ES-PO","Caldas de Reis",""},
{"Malmen Air Base","SE","SE-E","Linköping",""},
{"Uppsala Airport","SE","SE-C","",""},
{"Nyge Airport","SE","SE-D","Nyköping",""},
{"Lund Hospital Heliport","SE","SE-M","Lund",""},
{"Hasslosa Air Base","SE","SE-Q","Hasslosa",""},
{"Sjöbo Air Base","SE","SE-M","Sjöbo",""},
{"Kosta Air Base","SE","SE-G","Kosta",""},
{"Sandvik Airport","SE","SE-H","Sandvik",""},
{"Byholma Air Base","SE","SE-G","Byholma",""},
{"Ålleberg Airport","SE","SE-Q","Ålleberg",""},
{"Viared Airport","SE","SE-Q","Borås",""},
{"Gothenburg-Landvetter Airport","SE","SE-Q","Gothenburg","GOT"},
{"Herrljunga Airport","SE","SE-Q","Herrljunga",""},
{"Jönköping Airport","SE","SE-F","Jönköping","JKG"},
{"Lidköping-Hovby Airport","SE","SE-Q","Lidköping","LDK"},
{"Brännebrona Airport","SE","SE-Q","Götene",""},
{"Gothenburg City Airport","SE","SE-Q","Gothenburg","GSE"},
{"Skövde Airport","SE","SE-Q","Skövde","KVB"},
{"Trollhättan-Vänersborg Airport","SE","SE-Q","Trollhättan","THN"},
{"Varberg Getterön airfield","SE","SE-N","Varberg",""},
{"Karlsborg Air Base","SE","SE-Q","Karlsborg",""},
{"Gimo Air Base","SE","SE-C","Gimo",""},
{"Sundbro Airport","SE","SE-C","",""},
{"Gryttjom Airport","SE","SE-C","Gryttjom",""},
{"Karlskoga Airport","SE","SE-T","","KSK"},
{"Stockholm Skavsta Airport","SE","SE-D","Stockholm / Nyköping","NYO"},
{"Strängnäs Air Base","SE","SE-D","Strängnäs",""},
{"Sunne Airport","SE","SE-S","",""},
{"Björkvik Air Base","SE","SE-D","Björkvik",""},
{"Borglanda Airport","SE","SE-H","Borglanda",""},
{"Hässleholm Vankivar Airport","SE","SE-M","Hässleholm",""},
{"Fagerhult Airport","SE","SE-M","Fagerhult",""},
{"Höganäs Airport","SE","SE-M","Höganäs",""},
{"Kågeröd Airport","SE","SE-M","Kågeröd",""},
{"Landskrona Airport","SE","SE-M","Landskrona",""},
{"Oskarshamn Airport","SE","SE-H","","OSK"},
{"Kalmar Airport","SE","SE-H","","KLR"},
{"Malmö Sturup Airport","SE","SE-M","Malmö","MMX"},
{"Möckeln Airport","SE","SE-G","Älmhult",""},
{"Tingsryd Airport","SE","SE-G","Tingsryd",""},
{"Smålandsstenar Smålanda Airport","SE","SE-F","Smålandsstenar",""},
{"Hallviken Airport","SE","SE-Z","",""},
{"Hedlanda Airport","SE","SE-Z","Hede",""},
{"Överkalix Airport","SE","SE-BD","Överkalix",""},
{"Gällivare Airport","SE","SE-BD","Gällivare","GEV"},
{"Kubbe Air Base","SE","SE-Y","Kubbe",""},
{"Kramfors Sollefteå Airport","SE","SE-Y","Kramfors / Sollefteå","KRF"},
{"Optand Airport","SE","SE-Z","",""},
{"Örnsköldsvik Airport","SE","SE-Y","Örnsköldsvik","OER"},
{"Kiruna Airport","SE","SE-BD","","KRN"},
{"Skellefteå Airport","SE","SE-AC","Skellefteå","SFT"},
{"Umeå Airport","SE","SE-AC","Umeå","UME"},
{"Arvidsjaur Airport","SE","SE-BD","Arvidsjaur","AJR"},
{"Östersund Airport","SE","SE-Z","Östersund","OSD"},
{"Örebro Airport","SE","SE-T","Örebro","ORB"},
{"Karlstad Airport","SE","SE-S","Karlstad","KSD"},
{"Stockholm Västerås Airport","SE","SE-U","Stockholm / Västerås","VST"},
{"Luleå Airport","SE","SE-BD","Luleå","LLA"},
{"Vidsel Air Base","SE","SE-BD","Vidsel",""},
{"Hede Air Base","SE","SE-BD","",""},
{"Berga Airport","SE","SE-AB","Berga Naval Base",""},
{"Stockholm-Bromma Airport","SE","SE-AB","Stockholm","BMA"},
{"Borlange Airport","SE","SE-W","","BLE"},
{"Hultsfred Airport","SE","SE-H","","HLF"},
{"Laxå Airport","SE","SE-T","Laxå",""},
{"Gävle Sandviken Airport","SE","SE-X","Gävle / Sandviken","GVX"},
{"Brattforshede Airport","SE","SE-S","Lindfors",""},
{"Norrköping Airport","SE","SE-E","Norrköping","NRK"},
{"Karlstad South Airport","SE","SE-S","Karlstad",""},
{"Eskilstuna Airport","SE","SE-D","Eskilstuna","EKT"},
{"Västervik Airport","SE","SE-H","Västervik","VVK"},
{"Vängsö Airport","SE","SE-D","Vängsö",""},
{"Fjällbacka Anra Airport","SE","SE-Q","Fjällbacka",""},
{"Ljungbyhed Airport","SE","SE-M","Ljungbyhed",""},
{"Vellinge Airfield","SE","SE-M","Vellinge",""},
{"Arbrå Airport","SE","SE-X","Arbrå",""},
{"Idre Airport","SE","SE-W","Idre","IDB"},
{"Gargnäs Airport","SE","SE-AC","Gargnäs",""},
{"Mellansel Airport","SE","SE-Y","Mellansel",""},
{"Kalixfors Airport","SE","SE-BD","",""},
{"Mohed Airport","SE","SE-X","Mohed",""},
{"Pajala Airport","SE","SE-BD","","PJA"},
{"Åsele Airport","SE","SE-AC","Åsele",""},
{"Älvsbyn Airport","SE","SE-BD","Älvsbyn",""},
{"Avesta Airport","SE","SE-W","Avesta",""},
{"Gagnef Airport","SE","SE-W","Djurås",""},
{"Katrineholm Airport","SE","SE-D","Katrineholm",""},
{"Köping Airport","SE","SE-U","Köping",""},
{"Missão Catrinami Airport","BR","BR-RR","Caracaraí",""},
{"Mudubim I Airport","BR","BR-RR","Pacaraima",""},
{"Orinduque Airport","BR","BR-RR","Uiramutã",""},
{"Fazenda Mombaça Heliport","BR","BR-RJ","Angra Dos Reis",""},
{"Paapiu Novo Airport","BR","BR-RR","Iracema",""},
{"Pacu Airport","BR","BR-RR","Normândia",""},
{"Palimiú Airport","BR","BR-RR","Alto Alegre",""},
{"Pedra Branca Airport","BR","BR-RR","Uiramutã",""},
{"Piolho Airport","BR","BR-RR","Pacaraima",""},
{"Raposa Airport","BR","BR-RR","Normândia",""},
{"Santa Liberdade Airport","BR","BR-RR","Pacaraima",""},
{"Maragogipe Airport","BR","BR-MS","Itaquiraí",""},
{"São Miguel Cachoeirinha Airport","BR","BR-RR","Pacaraima",""},
{"Serra do Sol Airport","BR","BR-RR","Uiramutã",""},
{"Suapi Airport","BR","BR-RR","Pacaraima",""},
{"Clube de Esportes Aéreos e Náuticos do Pará Airport","BR","BR-PA","Belém",""},
{"Uraricoera Airport","BR","BR-RR","Alto Alegre",""},
{"Wapum Airport","BR","BR-RR","Bonfim",""},
{"Xidea Airport","BR","BR-RR","Alto Alegre",""},
{"Fazenda Mutum Airport","BR","BR-MT","Nova Mutum",""},
{"Fazenda Três Perobas Airport","BR","BR-RO","Santa Luzia D`Oeste",""},
{"Fazenda Santa Luzia Airport","BR","BR-MT","Nova Mutum",""},
{"Fazenda Nazaré Airport","BR","BR-MS","Corumbá",""},
{"Destilaria Medasa Airport","BR","BR-BA","Medeiros Neto",""},
{"Ilha dos Macacos Airport","BR","BR-MT","Paranaíta",""},
{"Fazenda Campo Alto Airport","BR","BR-MT","Ribeirão Cascalheira",""},
{"Fazenda Nhandu Airport","BR","BR-MT","Novo Mundo",""},
{"Iberostar Praia do Forte Heliport","BR","BR-BA","Mata De São João",""},
{"Fazenda Fortaleza Heliport","BR","BR-SP","Taubaté",""},
{"Hotel Paradise Heliport","BR","BR-SP","Catanduva",""},
{"Haras Cachoeira Heliport","BR","BR-SP","Itu",""},
{"Ariquemes Airport","BR","BR-RO","Ariquemes",""},
{"Fazenda Jaguatirica Airport","BR","BR-MS","Porto Murtinho",""},
{"Fazenda Modelo Airport","BR","BR-MS","Água Clara",""},
{"Fazenda Karla Renata Airport","BR","BR-MT","Castanheira",""},
{"Doutor João Osmar de Oliveira Airport","BR","BR-MT","Comodoro",""},
{"Cristália Heliport","BR","BR-SP","Itapira",""},
{"Tropical Heliport","BR","BR-MG","Nova Serrana",""},
{"C.B.E. - Companhia Brasileira de Equipamentos Heliport","BR","BR-SP","Ribeirão Grande",""},
{"Fazenda Brinquinho Airport","BR","BR-BA","São Desidério",""},
{"Faria Lima Square Heliport","BR","BR-SP","São Paulo",""},
{"Guarapiranga Golfe Heliport","BR","BR-SP","São Paulo",""},
{"Riacho Verde Heliport","BR","BR-PE","Bezerros",""},
{"Polícia Federal Heliport","BR","BR-PR","Foz Do Iguaçu",""},
{"Fazenda Palma Airport","BR","BR-GO","Luziânia",""},
{"Prefeitura do Município de Jundiaí Heliport","BR","BR-SP","Jundiaí",""},
{"Fazenda Austrália Airport","BR","BR-MS","Deodápolis",""},
{"Campan Heliport","BR","BR-PR","Cambará",""},
{"Aero Rural Airport","BR","BR-MT","Alta Floresta",""},
{"Andrieli Base Operacional Airport","BR","BR-MT","Primavera Do Leste",""},
{"Petrobrás - Refinaria de Capuava Heliport","BR","BR-SP","Mauá",""},
{"Fazenda Guimarães Airport","BR","BR-MT","Lucas Do Rio Verde",""},
{"Fazenda Cidade Verde Airport","BR","BR-MT","Poxoréo",""},
{"Fazenda Santo Antônio Heliport","BR","BR-MA","Matinha",""},
{"Fazenda Symalu Airport","BR","BR-PA","Cumaru Do Norte",""},
{"Fazenda São Roque do Vale do Rio Negro Airport","BR","BR-MS","Aquidauana",""},
{"Fazenda Londrina Airport","BR","BR-MT","Campo Novo Do Parecis",""},
{"Fazenda Tempero Seco Airport","BR","BR-AM","Lábrea",""},
{"Jomarca II Heliport","BR","BR-SP","Guarujá",""},
{"Fazenda Lago Azul Heliport","BR","BR-MA","Igarapé Do Meio",""},
{"Unidade Administrativa Conjunta do IAP/BPAMB Heliport","BR","BR-PR","Paranaguá",""},
{"Jacarezinho Airport","BR","BR-SP","Valparaíso",""},
{"Fazenda Haras RPC Airport","BR","BR-MG","Nova Lima",""},
{"Usina Santa Luiza Airport","BR","BR-SP","Motuca",""},
{"Fazenda Uruará Airport","BR","BR-PA","Uruará",""},
{"Dona Iracema Airport","BR","BR-TO","Porto Nacional",""},
{"Fazenda VR Airport","BR","BR-MT","Santa Cruz Do Xingu",""},
{"Ilha Josefa Heliport","BR","BR-RJ","Angra Dos Reis",""},
{"Lavalpa Heliport","BR","BR-SP","Jacareí",""},
{"Fazenda Galheiro Airport","BR","BR-MT","Campo Verde",""},
{"Agromineral Mutum Airport","BR","BR-PA","Itaituba",""},
{"Fazenda do Açucar Airport","BR","BR-MT","Nobres",""},
{"Carlos Gomes Center Heliport","BR","BR-RS","Porto Alegre",""},
{"Fazenda Santângelo Agropecuária Airport","BR","BR-MS","Miranda",""},
{"Fazenda Barreiro Airport","BR","BR-GO","Paraúna",""},
{"Fazenda Arrendamento Airport","BR","BR-MT","Paranatinga",""},
{"PCH Garganta da Jararaca Airport","BR","BR-MT","Nova Maringá",""},
{"Grupamento Aéreo da Polícia Militar Heliport","BR","BR-SP","Praia Grande",""},
{"João Domingues de Araújo Heliport","BR","BR-SP","São Paulo",""},
{"Ilha Guaíba Heliport","BR","BR-RJ","Mangaratiba",""},
{"Fazenda São Bento Airport","BR","BR-MS","Sidrolândia",""},
{"Agropecuária Barrinha Airport","BR","BR-MG","São Francisco Sales",""},
{"Sonhar Airport","BR","BR-SC","Governador Celso Ramos",""},
{"Mário Spada Airport","BR","BR-MG","Minas Novas",""},
{"Fazenda Santa Rita Airport","BR","BR-GO","Itarumã",""},
{"Fazenda Divisão II Airport","BR","BR-MT","Lucas Do Rio Verde",""},
{"Fazenda Santa Rosa Airport","BR","BR-GO","Mara Rosa",""},
{"Umbará Energy Heliport","BR","BR-PR","Curitiba",""},
{"Natal Mar Heliport","BR","BR-RN","Natal",""},
{"Usina Mundial Heliport","BR","BR-SP","Mirandópolis",""},
{"Fazenda Buriti Airport","BR","BR-MT","Chapada Dos Guimarães",""},
{"Plaza JK Heliport","BR","BR-SP","São Paulo",""},
{"Fazenda Mequens Airport","BR","BR-RO","Alta Floresta D`Oeste",""},
{"Fazenda Iapó Airport","BR","BR-PR","Tibagi",""},
{"Ecofly Airport","BR","BR-SP","Brotas",""},
{"Santa Cecília Airport","BR","BR-SP","Mirandópolis",""},
{"São José Airport","BR","BR-MT","Campo Novo Do Parecis",""},
{"Fazenda Santa tereza Airport","BR","BR-RJ","Petrópolis",""},
{"Terra Santa Airport","BR","BR-PA","Terra Santa",""},
{"Fazenda Tucano Airport","BR","BR-MT","Campo Novo Do Parecis",""},
{"Centauro Heliport","BR","BR-PE","Igarassu",""},
{"Gran Meliá Mofarrej Heliport","BR","BR-SP","São Paulo",""},
{"Fazenda Ipanema Airport","BR","BR-BA","Correntina",""},
{"Jardim Paraíso Airport","BR","BR-BA","Luís Eduardo Magalhães",""},
{"Ecological Center Heliport","BR","BR-SP","Barueri",""},
{"Fazenda Lagoinha Airport","BR","BR-MG","Pedrinópolis",""},
{"Fazenda Juína Airport","BR","BR-MT","Campos De Júlio",""},
{"Fazenda Rio Pardo Airport","BR","BR-SP","Iaras",""},
{"Unimed - Nordeste Heliport","BR","BR-RS","Caxias Do Sul",""},
{"Braskem Heliport","BR","BR-BA","Camaçari",""},
{"Fazenda Acará Airport","BR","BR-GO","Britânia",""},
{"Fazenda Paraná Airport","BR","BR-GO","Nova Roma",""},
{"CPFL Sede Heliport","BR","BR-SP","Campinas",""},
{"Sinal Empreendimentos Heliport","BR","BR-RJ","Rio Das Ostras",""},
{"DJY Heliport","BR","BR-SP","São Paulo",""},
{"Ibiporanga da Felicidade Airport","BR","BR-SP","Tanabi",""},
{"VR Campos do Jordão Heliport","BR","BR-SP","Campos Do Jordão",""},
{"Jacarecica Heliport","BR","BR-AL","Maceió",""},
{"Viana II Heliport","BR","BR-SC","Itapema",""},
{"Fazenda Cachoeirinha Airport","BR","BR-MG","Perdizes",""},
{"Fazenda do Limão Airport","BR","BR-PA","Almeirim",""},
{"Vila Pitinga Airport","BR","BR-AM","Presidente Figueiredo",""},
{"Fazenda São Joaquim Airport","BR","BR-MS","Jardim",""},
{"Cimento Rio Negro-Cantagalo Heliport","BR","BR-RJ","Cantagalo",""},
{"Fazenda Catelani Airport","BR","BR-GO","Minaçu",""},
{"Pagrisa Airport","BR","BR-PA","Ulianópolis",""},
{"Fazenda São Paulo Airport","BR","BR-MT","Sapezal",""},
{"Pouso Alto Airport","BR","BR-GO","Piracanjuba",""},
{"Usina Passa Tempo Airport","BR","BR-MS","Rio Brilhante",""},
{"Mima Heliport","BR","BR-RJ","São João Da Barra",""},
{"Fazenda Santa Inês Airport","BR","BR-MT","Nova Brasilândia",""},
{"HPE Heliport","BR","BR-SP","São Paulo",""},
{"Boca da Mata Airport","BR","BR-MT","Gaúcha Do Norte",""},
{"Fazenda Santa Dulcina Airport","BR","BR-SP","Taquarituba",""},
{"Warpol Airport","BR","BR-BA","São Desidério",""},
{"Heligalo Heliport","BR","BR-RJ","Angra Dos Reis",""},
{"Fazenda Sucuri Airport","BR","BR-MT","Itiquira",""},
{"Fazenda São Judas Airport","BR","BR-GO","São Miguel Do Araguaia",""},
{"Rio Alegre Airport","BR","BR-SP","Euclides Da Cunha Paulista",""},
{"E-Tower Heliport","BR","BR-SP","São Paulo",""},
{"Aquapey Airport","BR","BR-MT","Porto Esperdião",""},
{"Escarpas Heliport","BR","BR-MG","Capitólio",""},
{"Aloiso Ximenes de Farias Junior Heliport","BR","BR-CE","Trairi",""},
{"Águas Frias Airport","BR","BR-RS","Iraí",""},
{"Parque Fazenda Bom Futuro Airport","BR","BR-MT","Poconé",""},
{"Alice Maria Sampaio Ferreira Heliport","BR","BR-SP","São Paulo",""},
{"B. Cao Viño Heliport","BR","BR-SP","Praia Grande",""},
{"Iguassú Heliport","BR","BR-RJ","Angra Dos Reis",""},
{"Fazenda Bela Vista Airport","BR","BR-MS","Amambaí",""},
{"Recreio Airport","BR","BR-MS","Ponta Porã",""},
{"Namour Heliport","BR","BR-SP","São Paulo",""},
{"Edifício Plaza I Heliport","BR","BR-SP","São Paulo",""},
{"Fazenda Kajussol Airport","BR","BR-RO","Santa Luzia D`Oeste",""},
{"Ajarani Airport","BR","BR-RR","Caracaraí",""},
{"Araí Airport","BR","BR-RR","Pacaraima",""},
{"Baixo Catrimani Airport","BR","BR-RR","Caracaraí",""},
{"Bala Airport","BR","BR-RR","Pacaraima",""},
{"Bananeira Airport","BR","BR-RR","Uiramutã",""},
{"Camará Airport","BR","BR-RR","Normândia",""},
{"Campo Grande Airport","BR","BR-RR","Pacaraima",""},
{"Fazenda Santa Terezinha Airport","BR","BR-MT","Santa Terezinha",""},
{"Fazenda Lagoa Encantada Airport","BR","BR-MT","Primavera Do Leste",""},
{"Vale do Tucanã Airport","BR","BR-MT","Castanheira",""},
{"Fazenda Bandeiras Airport","BR","BR-MS","Corumbá",""},
{"Fazenda Campo Triste Airport","BR","BR-MS","Três Lagoas",""},
{"Fazenda Rio do Fogo Airport","BR","BR-MT","Nova Santa Helena",""},
{"Rancho Dória Heliport","BR","BR-SP","Campos Do Jordão",""},
{"Daslu Heliport","BR","BR-SP","São Paulo",""},
{"Costa Brasilis Heliport","BR","BR-BA","Santa Cruz Cabrália",""},
{"Mathovi Airport","BR","BR-MT","Novo Mundo",""},
{"Fazenda Itália Airport","BR","BR-PI","Uruçui",""},
{"Fazenda Busato II Airport","BR","BR-BA","Serra Ramalho",""},
{"Terras de São José Heliport","BR","BR-SP","Itu",""},
{"Fazenda Rebojo Airport","BR","BR-MS","Corumbá",""},
{"Fazenda Passo Fundo Airport","BR","BR-MT","Primavera Do Leste",""},

{"Terminal Petrobrás - Guarulhos Heliport","BR","BR-SP","Guarulhos",""},
{"Hospital Santa Joana Heliport","BR","BR-PE","Recife",""},
{"Fazenda Água Branca Airport","BR","BR-MS","Santa Rita Do Pardo",""},
{"Fazenda Colorado Airport","BR","BR-TO","Lagoa Da Confusão",""},
{"Usina Mandu Airport","BR","BR-SP","Guaíra",""},
{"Fazenda Vista Alegre Airport","BR","BR-SP","Sud Menucci",""},
{"Fazenda Vaca Branca Airport","BR","BR-MS","Naviraí",""},
{"Fazenda Alvorada Airport","BR","BR-PR","Quarto Centenário",""},
{"Rancho Donana Airport","BR","BR-SP","Cerqueira César",""},
{"Fazenda Paquetá Airport","BR","BR-MS","Ponta Porã",""},
{"Fazenda Cedro Airport","BR","BR-MS","Ponta Porã",""},
{"Fazenda Santa Claudina Airport","BR","BR-MS","Caarapó",""},
{"Veranópolis Airport","BR","BR-RS","Veranópolis",""},
{"Silangit Airport","ID","ID-SU","Tingkeum-Sumatra Island",""},
{"Pematang Siantar","ID","ID-SU","Pematang Siantar-Sumatra Island",""},
{"Tebing Tinggi Airport","ID","ID-SU","Tabbing Tinggi-Sumatra Island",""},
{"Surabaya Airport","ID","ID-JI","Surabaya-Java Island",""},
{"Polish Paradise Airport","US","US-WI","Oxford","WS02"},
{"Zanadu Airport","US","US-WI","Arkdale","WS04"},
{"Springstead Airport","US","US-WI","Park Falls","WS06"},
{"Five Corners Airways Airport","US","US-WI","Appleton","WS08"},
{"Casey Lake Airport","US","US-WI","Waupaca","WS10"},
{"Elert Airport","US","US-WI","De Forest","WS12"},
{"Lake Ell Field","US","US-WI","Amherst","WS14"},
{"Scherrico Meadows Airport","US","US-WI","Mosinee","WS16"},
{"Aurora Sheboygan Memorial Medical Center Heliport","US","US-WI","Sheboygan","WS18"},
{"Young Tactical Landing Site Airport","US","US-WI","Fort Mc Coy","WS20"},
{"Wolfgram Airport","US","US-WI","New London","WS22"},
{"Round Lake Seaplane Base","US","US-WI","Hayward","WS24"},
{"Ranch Side Airport","US","US-WI","Kewaunee","WS26"},
{"Coleman Airport","US","US-WI","Portage","WS28"},
{"Hexum Flight Park Ultralightport","US","US-WI","Star Prairie","WS30"},
{"Prescott Field","US","US-WI","Wyocena","WS32"},
{"Fort Atkinson Memorial Hospital Heliport","US","US-WI","Fort Atkinson","WS34"},
{"Swan Field","US","US-WI","Almond","WS36"},
{"Luther Hospital Heliport","US","US-WI","Eau Claire","WS38"},
{"Mercy Hospital Heliport","US","US-WI","Janesville","WS40"},
{"Owen-Withee Airport","US","US-WI","Withee","WS42"},
{"Diderrich Ranch Airport","US","US-WI","Hawkins","WS44"},
{"J & L Aviation Airport","US","US-WI","Ripon","WS46"},
{"Memorial Hospital Heliport","US","US-WI","Boscobel","WS48"},
{"Mercy Medical Center Heliport","US","US-WI","Oshkosh","WS50"},
{"St Marys Hospital Medical Center Heliport","US","US-WI","Madison","WS52"},
{"Reedsburg Memorial Hospital Heliport","US","US-WI","Reedsburg","WS54"},
{"St Nicholas Hospital Heliport","US","US-WI","Sheboygan","WS56"},
{"Spooner Hospital Heliport","US","US-WI","Spooner","WS58"},
{"Vern Air Park","US","US-WI","Thorp","WS60"},
{"Sugar Ridge Airport","US","US-WI","Verona","WS62"},
{"Schiffmann Seaplane Base","US","US-WI","St Germain","WS64"},
{"St Joseph's Community Hospital Heliport","US","US-WI","West Bend","WS66"},
{"Krist Island Airport","US","US-WI","Montello","WS68"},
{"Beaver Dam Community Hospital Heliport","US","US-WI","Beaver Dam","WS70"},
{"Cain's Field","US","US-WI","Stiles","WS72"},
{"Al's Airway Airport","US","US-WI","Watertown","WS74"},
{"Black Dog Farm Airport","US","US-WI","New London","WS76"},
{"River Valley Airport","US","US-WI","Rhinelander","WS78"},
{"Alpha Hotel Airport","US","US-WI","Webster","WS81"},
{"Port Field","US","US-WA","Twisp","WS87"},
{"Hughes Airport","US","US-WI","Monroe","WS96"},
{"Grays Harbor Community Hospital Heliport","US","US-WA","Aberdeen","WT00"},
{"Hammer Evoc Skid Pad Heliport","US","US-WA","Richland","WT02"},
{"Deer Park / Radial Flyer Airport","US","US-WA","",""},
{"Kiwi Air Heliport","US","US-WA","Clarkston","WT28"},
{"Blaine Sectors Hqs Heliport","US","US-WA","Blaine","WT34"},
{"Rocky Bay Airport","US","US-WA","Vaughn","WT77"},
{"Lee Massey Airport","US","US-WV","Ansted","WV01"},
{"Lee Norse Nr 2 Heliport","US","US-WV","Beckley","WV03"},
{"Va Medical Center Heliport","US","US-WV","Martinsburg","WV05"},
{"State Police Heliport","US","US-WV","Charleston","WV07"},
{"Mike Ferrell Field","US","US-WV","Corinne","WV09"},
{"Swope Farm Airport","US","US-WV","Fan Rock","WV11"},
{"Minnick's Heliport","US","US-WV","Upland","WV13"},
{"Gerstell Farms Airport","US","US-WV","Keyser","WV15"},
{"Michaels Farms Airport","US","US-WV","Martinsburg","WV17"},
{"Moore Field","US","US-WV","Kingwood","WV19"},
{"Needwood Farm Airport","US","US-WV","Harpers Ferry","WV21"},
{"Louis Bennett Field","US","US-WV","Weston","WV23"},
{"Mount Storm Heliport","US","US-WV","Mount Storm","WV25"},
{"Cabell Huntington Hospital Heliport","US","US-WV","Huntington","WV27"},
{"Valley Point Airport","US","US-WV","Valley Point","WV29"},
{"Pratt Mining Heliport","US","US-WV","Lewisburg","WV31"},
{"Beckley Hotel Heliport","US","US-WV","Beckley","WV33"},
{"Pomeroy-Mason Seaplane Base","US","US-WV","Mason","WV35"},
{"New Martinsville Seaplane Base","US","US-WV","New Martinsville","WV37"},
{"Ravenswood Seaplane Base","US","US-WV","Ravenswood","WV39"},
{"East Liverpool Seaplane Base","US","US-WV","East Liverpool - Chester","WV41"},
{"Warwood - Martins Ferry Seaplane Base","US","US-WV","Wheeling","WV43"},
{"Princeton Community Hospital Heliport","US","US-WV","Princeton","WV45"},
{"Rexroad Airport","US","US-WV","Clarksburg","WV47"},
{"Center Wheeling Parking Garage Heliport","US","US-WV","Wheeling","WV49"},
{"University Hospital Heliport","US","US-WV","Morgantown","WV51"},
{"Larew Airport","US","US-WV","Newburg","WV53"},
{"Camc-Memorial Heliport","US","US-WV","Charleston","WV56"},
{"Pleasant Valley Hospital Heliport","US","US-WV","Point Pleasant","WV58"},
{"Walker Iii Heliport","US","US-WV","Crab Orchard","WV60"},
{"Windwood Fly-In Resort Airport","US","US-WV","Davis","WV62"},
{"Scott Field","US","US-WV","Mineral Wells","WV64"},
{"Durrett Ranches Airport","US","US-WV","Belington","WV68"},
{"Fairview Airport","US","US-WV","Elkins","WV70"},
{"Philip Sporn Plant Heliport","US","US-WV","New Haven","WV72"},
{"Snowshoe Heliport","US","US-WV","Snowshoe","WV74"},
{"Slate Run Airport","US","US-WV","Spencer","55I"},
{"Rach Heliport","US","US-WV","Richwood","WV78"},
{"Red Reflet Ranch Airport","US","US-WY","Ten Sleep","WY00"},
{"Iberlin Ranch Nr 3 Airport","US","US-WY","Bill","WY02"},
{"Powell Hospital Heliport","US","US-WY","Powell","WY04"},
{"Luckinbill Airstrip","US","US-WY","Cody","WY06"},
{"Johnson Heliport","US","US-WY","Jackson","WY08"},
{"Two Jays Six Heliport","US","US-WY","Fort Washakie","WY10"},
{"Ohman Ranch Airport","US","US-WY","Gillette","WY12"},
{"Ipy Ranch Airport","US","US-WY","Hulett","WY14"},
{"Robbins Airport","US","US-WY","Medicine Bow","WY16"},
{"Iberlin Ranch Nr 2 Airport","US","US-WY","Midwest","WY18"},
{"Johnson Heliport","US","US-WY","Jackson","WY20"},
{"Iberlin Ranch Nr 1 Airport","US","US-WY","Savageton","WY22"},
{"Riverton Memorial Hospital Heliport","US","US-WY","Riverton","WY24"},
{"Community Hospital Heliport","US","US-WY","Torrington","WY26"},
{"Pinedale Medical Clinic Heliport","US","US-WY","Pinedale","WY28"},
{"Kinky Creek Divide Airport","US","US-WY","Dubois","WY30"},
{"Antelope Run Ranch Airport","US","US-WY","Daniel","WY33"},
{"Washakie Memorial Hospital Heliport","US","US-WY","Worland","WY35"},
{"Symons Airport","US","US-WY","Sheridan","WY37"},
{"Star Valley Ranch Airport","US","US-WY","Thayne","WY39"},
{"Red Creek Ranch Airport","US","US-WY","Rock Springs","WY41"},
{"Sloan Airport","US","US-WY","Cheyenne","WY45"},
{"True Heliport","US","US-WY","Casper","WY47"},
{"Cheyenne Echo Heliport","US","US-WY","Cheyenne","WY50"},
{"Evanston Regional Hospital Heliport","US","US-WY","Evanston","WY52"},
{"Wyoming Medical Center Heliport","US","US-WY","Casper","WY57"},
{"Heiner Airport","US","US-WY","Afton","WY60"},
{"West Park Hospital Heliport","US","US-WY","Cody","WY62"},
{"Madsen Airport","US","US-WY","Gillette","WY65"},
{"South Lincoln Medical Center Heliport","US","US-WY","Kemmerer","WY67"},
{"Salmo Airport","CA","CA-BC","Salmo",""},
{"Denver Stapleton International Airport","US","US-CO","Denver",""},
{"Bacolod City Domestic Airport","PH","PH-NEC","Bacolod City",""},
{"Aspern Airfield","AT","AT-9","Vienna",""},
{"Covey Trails Airport","US","US-TX","Fulshear","X09"},
{"Chalet Suzanne Air Strip","US","US-FL","Lake Wales","X25"},
{"Buchan Airport","US","US-FL","Englewood","X36"},
{"Miami Heliport","US","US-FL","Miami","X48"},
{"Mid Florida Air Service Airport","US","US-FL","Eustis","X55"},
{"Patillas Airport","PR","PR-U-A","Patillas","X64"},
{"Cozby-Germany Hospital Heliport","US","US-TX","Grand Saline","XA01"},
{"Edgington Ranch Airport","US","US-TX","Sanger","XA03"},
{"Fairview Field","US","US-TX","Sudan","XA05"},
{"Spectre Airport","US","US-TX","Chico","XA07"},
{"Menard Airport","US","US-TX","Bellevue","XA09"},
{"Lake Pointe Medical Center Heliport","US","US-TX","Rowlett","XA11"},
{"Landry's Seafood House Heliport","US","US-TX","Houston","XA13"},
{"Chuckster Airport","US","US-TX","Tira","XA17"},
{"Drv Downtown Houston Aquarium Heliport","US","US-TX","Houston","XA19"},
{"Las Colinas Medical Center Heliport","US","US-TX","Irving","XA21"},
{"Richardson Field","US","US-TX","Pittsburg","XA23"},
{"Lubbock Heart Hospital Heliport","US","US-TX","Lubbock","XA25"},
{"Etmc - Pittsburg Heliport","US","US-TX","Pittsburg","XA27"},
{"Heart Hospital of San Antonio Heliport","US","US-TX","San Antonio","XA29"},
{"Lewis Ranch Airport","US","US-TX","Leakey","XA31"},
{"Thorny Woods Airport","US","US-TX","Caddo Mills","XA33"},
{"Southwest Rains Vol Fire Department Heliport","US","US-TX","Flats","XA35"},
{"Plaza Medical Center Heliport","US","US-TX","Fort Worth","XA37"},
{"Etmc - Gilmer Heliport","US","US-TX","Gilmer","XA39"},
{"Lone Star Flying Service Airport","US","US-TX","Harper","XA41"},
{"Fall Creek Ranch Airport","US","US-TX","Kerrville","XA43"},
{"Weedfalls Airport","US","US-TX","Lone Oak","XA45"},
{"Tick Hill Airfield","US","US-TX","Moody","XA47"},
{"Oso Canyon Airport","US","US-TX","Ozona","XA49"},
{"Smith Airport","US","US-TX","Robinson","XA51"},
{"Presbyterian Hospital Of Allen Heliport","US","US-TX","Allen","XA53"},
{"Presbyterian Hospital Of Greenville Heliport","US","US-TX","Greenville","XA56"},
{"Medical Center of Lewisville Heliport","US","US-TX","Lewisville","XA59"},
{"Baylor University Medical Center Dallas Heliport","US","US-TX","Dallas","XA61"},
{"AAF Heliport","US","US-TX","Lucas","XA63"},
{"Txaerosport Aerodrome","US","US-TX","Dorchester","XA65"},
{"Lebyazhye Air Base","RU","RU-VGG","Kamyshin",""},
{"Flying D Airport","US","US-TX","Llano","XS00"},
{"Tarrant County Water Control Heliport","US","US-TX","Fort Worth","XS02"},
{"East Texas Medical Center Crockett Heliport","US","US-TX","Crockett","XS04"},
{"Flying B Ranch Airport","US","US-TX","Grandview","XS06"},
{"Polk Ranch Airport","US","US-TX","Mason","XS08"},
{"Aransas National Wildlife Refuge Airport","US","US-TX","Matagorda Island","XS10"},
{"C F C Aviation Ranch Airport","US","US-TX","Liberty Hill","XS12"},
{"Weese International Airport","US","US-TX","Greenville","XS14"},
{"San Jacinto College Central Campus Heliport","US","US-TX","Pasadena","XS16"},
{"Tom J Moore Farm Airport","US","US-TX","Millican","XS18"},
{"Dos Arroyos Ranch Airport","US","US-TX","Mountain Home","XS20"},
{"Y O Ranch Airport","US","US-TX","Mountain Home","XS22"},
{"Cherry Spraying Service Airport","US","US-TX","Muldoon","XS24"},
{"Graco Mechanical Inc Heliport","US","US-TX","Houston","XS26"},
{"North Willis Airport","US","US-TX","Nome","XS28"},
{"Burress Airport","US","US-TX","Paris","XS30"},
{"Nucor Ems Heliport","US","US-TX","Jewett","XS32"},
{"Skylark Airport","US","US-TX","Ennis","XS34"},
{"Tres Ninos Ranch Airport","US","US-TX","Pandale","XS36"},
{"3321 Westside Heliport","US","US-TX","Pasadena","XS38"},
{"Jay Kay Ranch Airport","US","US-TX","Pearsall","XS40"},
{"Agricultural Supplies Airport","US","US-TX","Pearsall","XS42"},
{"Rancho Del Cielo Airport","US","US-TX","Kent","XS44"},
{"Port O'Connor Private Airport","US","US-TX","Port O'Connor","XS46"},
{"Marlin'S Meadow Airport","US","US-TX","Yantis","XS48"},
{"4-G Ranch Airport","US","US-TX","Premont","XS50"},
{"Lewis Heliport","US","US-TX","Premont","XS52"},
{"Arlington Marriott Hotel Heliport","US","US-TX","Arlington","XS54"},
{"Bell Airfield","US","US-TX","Raymondville","XS56"},
{"Tri-County Air Service Airport","US","US-TX","Raywood","XS58"},
{"Mustang Community Airfield","US","US-TX","Aubrey","XS60"},
{"Casey Three Ranch Airport","US","US-TX","Rio Frio","XS62"},
{"Farm Services Inc Airport","US","US-TX","Rio Hondo","XS64"},
{"Rabb Dusting Inc Airport","US","US-TX","Robstown","XS66"},
{"Sky Lane Ranch Airport","US","US-TX","Brenham","XS68"},
{"Glover Airport","US","US-TX","Mount Pleasant","XS70"},
{"F R Duke Farm Airport","US","US-TX","Romayor","XS72"},
{"Diamondaire Airport","US","US-TX","Waco","XS74"},
{"Texas Menhaden Strip","US","US-TX","Sabine Pass","XS76"},
{"Las Culebras Airport","US","US-TX","Brady","XS78"},
{"Santiago Cattle Co. Airport","US","US-TX","Comfort","XS80"},
{"Del Rio Heliport","US","US-TX","San Antonio","XS82"},
{"Department of Public Safety Heliport","US","US-TX","San Antonio","XS84"},
{"T-Ranch Airport","US","US-TX","Castroville","XS86"},
{"Parson Field","US","US-TX","Paris","XS88"},
{"Fentress Airpark","US","US-TX","Fentress","XS90"},
{"Jackson /Bill/ Airport","US","US-TX","Paradise","XS92"},
{"Corralitos Airport","US","US-TX","San Ygnacio","XS94"},
{"Hillwood Heliport","US","US-TX","Fort Worth","XS96"},
{"Guadalupe Hospital Heliport","US","US-TX","Seguin","XS98"},
{"Smolensk North Airport","RU","RU-SMO","Smolensk",""},
{"Vinh Long Airfield","VN","VN-49","Vinh Long","XVL"},
{"Sosnovka Airfield","RU","RU-PNZ","Penza",""},
{"Victoria STOLport","CA","CA-QC","Montreal",""},
{"Waukon Municipal Airport","US","US-IA","Waukon","Y01"},
{"Dale Delight Airport","US","US-IA","Postville","Y16"},
{"Lake Preston Municipal Airport","US","US-SD","Lake Preston","Y34"},
{"Belmond Municipal Airport","US","US-IA","Belmond","Y48"},
{"Sleepy Eye Municipal Airport","US","US-MN","Sleepy Eye","Y58"},
{"Elgin Municipal Airport","US","US-ND","Elgin","Y71"},
{"Morningstar Field","US","US-IA","Des Moines","Y76"},
{"Empire Airport","US","US-MI","Empire","Y87"},
{"Home Acres Sky Ranch Airport","US","US-MI","Lake City","Y91"},
{"Grand Marais Airport","US","US-MI","Grand Marais","Y98"},
{"Millrose Homestead Airport","AU","AU-WA","",""},
{"Mount Ive Airport","AU","AU-SA","",""},
{"Mount James Airport","AU","AU-WA","",""},
{"Mararanka Homestead Airport","AU","AU-NT","",""},
{"Emkaytee (Unlic) Airport","AU","AU-NT","",""},
{"Mole Creek Airport","AU","AU-TAS","",""},
{"Minnamoolka Airport","AU","AU-QLD","",""},
{"Monolon Airport","AU","AU-NSW","",""},
{"Miles Airport","AU","AU-QLD","",""},
{"Milurie Homestead Airport","AU","AU-WA","",""},
{"Murrin Murrin Airport","AU","AU-WA","",""},
{"Shannon River Airport","AU","AU-WA","",""},
{"Saint Arnaud Airport","AU","AU-VIC","",""},
{"Stuart Creek Airport","AU","AU-SA","Stuart Creek",""},
{"Stonehenge Airport","AU","AU-QLD","",""},
{"Santa Teresa Airport","AU","AU-NT","",""},
{"Supplejack Downs Airport","AU","AU-NT","",""},
{"Strathaven Airport","AU","AU-QLD","",""},
{"Sweers Island Resort Airport","AU","AU-QLD","",""},
{"Tenneco Station Five Airport","AU","AU-SA","",""},
{"Tenterfield Airport","AU","AU-NSW","Tenterfield",""},
{"Taggerty Airport","AU","AU-VIC","",""},
{"The Grove Airport","AU","AU-NSW","",""},
{"Thistle Island Airport","AU","AU-SA","Thistle Island",""},
{"Three Springs Airport","AU","AU-WA","",""},
{"Tullamore Airport","AU","AU-NSW","",""},
{"Tarlton Downs Airport","AU","AU-NT","",""},
{"Tamala Airport","AU","AU-WA","",""},
{"The Monument Airport","AU","AU-QLD","",""},
{"Truscott Mungalalu Airport","AU","AU-WA","",""},
{"Troughton Is Airport","AU","AU-WA","",""},
{"Triabunna Airport","AU","AU-TAS","",""},
{"Trugananni Airport","AU","AU-QLD","",""},
{"Wedderburn Airport","AU","AU-VIC","",""},
{"Wellington Airport","AU","AU-NSW","",""},
{"Wernadinga Airport","AU","AU-QLD","",""},
{"Western Field Airport","AU","AU-WA","",""},
{"Wee Jasper Airport","AU","AU-NSW","",""},
{"Woodycupaldiya Airfield","AU","AU-NT","Woodycupaldiya","YWKD"},
{"Waikerie Airport","AU","AU-SA","",""},
{"Wilkins Runway","AQ","AQ-U-A","",""},
{"Willowra Airport","AU","AU-NT","",""},
{"Williamsdale Airport","AU","AU-NSW","",""},
{"Wallara Ranch Airport","AU","AU-NT","",""},
{"Wooltana Airport","AU","AU-SA","",""},
{"Woorlba Airport","AU","AU-WA","",""},
{"Walpole Airport","AU","AU-WA","",""},
{"Wooroona Airport","AU","AU-QLD","",""},
{"Wirralie Airport","AU","AU-QLD","",""},
{"Albury Base Hospital Helipad","AU","AU-NSW","Albury","YXAL"},
{"Bundaberg Base Hospital Helipad","AU","AU-QLD","Bundaberg","YXBD"},
{"Batemans Bay Helipad","AU","AU-NSW","Batemans Bay","YXBM"},
{"Bulwer Heliport","AU","AU-QLD","Bulwer","YXBU"},
{"Canberra Hospital Helipad","AU","AU-ACT","Canberra","YXCB"},
{"Cherbourg Hospital Helipad","AU","AU-QLD","Cherbourg","YXCH"},
{"Cooma Hospital Helipad","AU","AU-NSW","Cooma","YXCM"},
{"Calvary - Bruce Oval Helipad","AU","AU-ACT","Canberra","YXCY"},
{"Denman Helicopter Landing Site","AU","AU-NSW","Denman","YXDE"},
{"Royal Darwin Hospital Helipad","AU","AU-NT","Darwin","YXDH"},
{"Dunwich Hospital Helipad","AU","AU-QLD","Dunwich","YXDU"},
{"Moree Hospital Helipad","AU","AU-NSW","Moree","YXEE"},
{"Esk Hospital Helipad","AU","AU-QLD","Esk","YXES"},
{"Newcastle Westpac Base Heliport","AU","AU-NSW","Newcastle",""},
{"Goulburn Hospital Helipad","AU","AU-NSW","Goulburn","YXGH"},
{"Goondiwindi Hospital Helipad","AU","AU-QLD","Goondiwindi","YXGO"},
{"Gilgandra Multi Purpose Service Helipad","AU","AU-NSW","Gilgandra","YXGR"},
{"Gunnedah Hospital Helipad","AU","AU-NSW","Gunnedah","YXGU"},
{"Hervey Bay Hospital Helipad","AU","AU-QLD","Hervery Bay","YXHE"},
{"John Hunter Hospital Helipad","AU","AU-NSW","Newcastle","YXJH"},
{"Kempsey Hospital Helicopter Landing Site","AU","AU-NSW","Kempsey","YXKE"},
{"Kyogle Hospital Helipad","AU","AU-NSW","Kyogle","YXKO"},
{"Laidley Hospital Helipad","AU","AU-QLD","Laidley","YXLA"},
{"Lithgow Hospital Helipad","AU","AU-NSW","Lithgow","YXLG"},
{"Caboolture Hospital Helipad","AU","AU-QLD","Caboolture","YXLT"},
{"Mount Druitt Hospital Heliport","AU","AU-NSW","Mount Druitt","YXMD"},
{"Mudgee Hospital Helipad","AU","AU-NSW","Mudgee","YXMH"},
{"Mullumbimby Hospital Helipad","AU","AU-NSW","Mullumbimby","YXMU"},
{"Merriwa Hospital Helipad","AU","AU-NSW","Merriwa","YXMW"},
{"Nambour Hospital Helipad","AU","AU-QLD","Nambour","YXNA"},
{"Nanango Hospital Helipad","AU","AU-QLD","Nanango","YXNN"},
{"Nowra Hospital Helipad","AU","AU-QLD","Nowra","YXNW"},
{"Orange Hospital Helipad","AU","AU-NSW","Orange","YXOG"},
{"Pindarra Hospital Helipad","AU","AU-QLD","Gold Coast","YXPI"},
{"Port Macquarie Hospital Helipad","AU","AU-NSW","Port Macquarie","YXPM"},
{"Quirindi Hospital Helipad","AU","AU-NSW","Quirindi","YXQU"},
{"Sydney Adventist Hospital Helipad","AU","AU-NSW","Wahroonga","YXSA"},
{"St George Hospital Helipad","AU","AU-NSW","Kogarah","YXSG"},
{"Singleton Hospital Helipad","AU","AU-NSW","Singleton","YXSI"},
{"Tangalooma Resort Airport","AU","AU-QLD","",""},
{"Trundle Hospital Helicopter Landing Site","AU","AU-NSW","Trundle","YXTN"},
{"Tumut Hospital Helipad","AU","AU-NSW","Tumut","YXTT"},
{"Wagga - Duke of Kent Oval Helipad","AU","AU-NSW","Wagga","YXWG"},
{"Wellington-Rygate Park Heliport","AU","AU-NSW","Wellington","YXWT"},
{"Wyong Hospital Helipad","AU","AU-NSW","Wyong","YXWY"}};

}
