

doc:
	erl -noshell -run edoc_run files  '["../src/database/get_database.erl","../src/database/make_db.erl","../src/database/consair_database.erl","../src/backend/booking_agent.erl","../src/backend/server.erl","../src/backend/package_handler.erl","../src/backend/server_utils.erl"]' 
